# These are supported funding model platforms

github: ewerspej # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
buy_me_a_coffee: ewerspej # Replace with a single Buy Me a Coffee username
